// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.interactions.Actions;

import java.util.HashMap;
import java.util.Map;

public class FormTest {
    JavascriptExecutor js;
    private WebDriver driver;
    private Map<String, Object> vars;

    @Before
    public void setUp() {
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void form() {
        driver.get("https://demoqa.com/automation-practice-form");
        driver.manage().window().setSize(new Dimension(1854, 1048));
        driver.findElement(By.id("firstName")).click();
        driver.findElement(By.id("firstName")).sendKeys("Agathe");
        driver.findElement(By.id("lastName")).sendKeys("Bauer");
        driver.findElement(By.id("userEmail")).sendKeys("agathe.bauer@yahoo.de");
        driver.findElement(By.cssSelector(".custom-radio:nth-child(2) > .custom-control-label")).click();
        driver.findElement(By.id("userNumber")).click();
        driver.findElement(By.id("userNumber")).sendKeys("0031456928");
        driver.findElement(By.id("dateOfBirthInput")).click();
        driver.findElement(By.cssSelector(".react-datepicker__year-select")).click();
        {
            WebElement dropdown = driver.findElement(By.cssSelector(".react-datepicker__year-select"));
            dropdown.findElement(By.xpath("//option[. = '1935']")).click();
        }
        driver.findElement(By.cssSelector("option:nth-child(36)")).click();
        driver.findElement(By.id("userForm")).click();
        driver.findElement(By.cssSelector(".subjects-auto-complete__value-container")).click();
        driver.findElement(By.id("subjectsInput")).sendKeys("None");
        driver.findElement(By.cssSelector(".custom-checkbox:nth-child(2) > .custom-control-label")).click();
        driver.findElement(By.cssSelector(".custom-checkbox:nth-child(3) > .custom-control-label")).click();
        driver.findElement(By.cssSelector(".custom-checkbox:nth-child(2) > .custom-control-label")).click();
        driver.findElement(By.id("currentAddress")).click();
        driver.findElement(By.id("submit")).click();
        {
            WebElement element = driver.findElement(By.id("submit"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            WebElement element = driver.findElement(By.tagName("body"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element, 0, 0).perform();
        }
        driver.findElement(By.id("closeLargeModal")).click();
    }
}
