// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import java.util.List;

public class HandsOnPurchaseTShirtTest {
    JavascriptExecutor js;
    private WebDriver driver;

    @Before
    public void setUp() {
//        System.setProperty("webdriver.gecko.driver", "/snap/bin/geckodriver"); // specify driver location if Selenium doesn't find it by itself
//        final FirefoxOptions options = new FirefoxOptions(); // uncomment for headless mode
//        options.addArguments("--headless");
//        driver = new FirefoxDriver(options);
        driver = new FirefoxDriver();
        js = (JavascriptExecutor) driver;
    }

    @After
    public void tearDown() {
        driver.quit();
    }

//    @Test
    public void purchaseTShirt() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(927, 1048));
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("standard_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"add-to-cart-sauce-labs-bolt-t-shirt\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"shopping-cart-link\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"checkout\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"firstName\"]")).sendKeys("Arthur");
        driver.findElement(By.cssSelector("*[data-test=\"lastName\"]")).sendKeys("Dent");
        driver.findElement(By.cssSelector("*[data-test=\"postalCode\"]")).sendKeys("42");
        driver.findElement(By.cssSelector("*[data-test=\"continue\"]")).click();
        driver.findElement(By.cssSelector("*[data-test=\"finish\"]")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector("*[data-test=\"pony-express\"]"));
            assert (elements.size() > 0);
        }
    }
}
